name: suiteefy_pos
description: excel as db , based pos system for suiteefy
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.1
  file_picker: ^8.0.0
  csv: ^6.0.0
  mobile_scanner: ^5.0.0
  intl: ^0.19.0
  flutter_contacts: ^1.1.7
  permission_handler: ^11.3.1
  pdf: ^3.11.0
  printing: ^5.13.2
  google_fonts: ^6.2.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-logosuiteefy.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
